### ISSUE TITLE
CSS RESET

### ISSUE THREAD

**Issue by amirdev98** [amirdev98/all-human-accessible-website-Amir.VA#4]
Deze reset altijd toevoegen.
```css
/* GLOBAL RESEST */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  scroll-behavior: smooth;
}

button {
  cursor: pointer;
}

a {
  text-decoration: none;
}

li {
  list-style: none;
}

```
